---
- name: Creates keypair, vpc, security group, deploys ec2
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - ec2-key
    - vpc
    - sg
    - ec2-instances

- name: deploys frontend software
  hosts: frontend_hosts
  gather_facts: true
  become: true
  user: ubuntu
  roles:
    - frontend

- name: deploys db software
  hosts: db_hosts
  gather_facts: true
  become: true
  user: ubuntu
  roles:
    - database

- name: deploys backend software
  hosts: backend_hosts
  gather_facts: true
  become: true
  user: ubuntu
  roles:
    - backend
