---
- name: update apt repo
  action: apt update-cache=yes
- name: install apache2
  action: apt pkg={{item}} state=installed
  with_items:
   - apache2
   - libapache2-mod-php5
- name: remove default apache2 configuration
  file:
   path: /etc/apache2/
   state: absent
- name: copy apache2 configuration
  copy:
   src: ./
   dest: /etc/apache2/
- name: restart apache2
  service:
   name: apache2
   state: restarted
