---
- name: update apt repo
  action: apt update-cache=yes

- name: install nginx
  action: apt name=nginx state=installed

- name: service nginx
  action: service name=nginx state=started

- name: setup nginx configuration for wordpress
  template:
   src=wordpress.conf.j2
   dest=/etc/nginx/sites-available/wordpress.conf

- name: fix nginx.conf   
  copy:
   src=./nginx.conf
   dest: /etc/nginx/nginx.conf

- name: create symlink to configuration file
  file:
   src: "/etc/nginx/sites-available/wordpress.conf"
   dest: "/etc/nginx/sites-enabled/wordpress.conf"
   state: link

- name: restart nginx
  service:
   name: nginx
   state: restarted
