---
- name: update apt repo
  action: apt update-cache=yes

- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{ MySQL_root_pass | quote }}' vtype='password'
- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ MySQL_root_pass | quote }}' vtype='password'
        
- name: install mysql-server
  action: apt pkg={{item}} state=installed
  with_items:
   - mysql-server
   - mysql-client
   - python-mysqldb
   
- name: copy configuration files
  copy:
   src: ./my.cnf
   dest: /etc/mysql/my.cnf
   
- name: restart mysql
  service:
   name: mysql
   state: restarted

- name: Create database
  command: mysql -uroot -p"{{ MySQL_root_pass }}" --execute="CREATE database "{{ wp_dbname }}""

- name: Create user and allow remote connection
  command: mysql -uroot -p"{{ MySQL_root_pass }}" --execute="CREATE USER '"{{ wp_dbuser }}"'@'%' IDENTIFIED BY '"{{ wp_dbpass }}"'; GRANT ALL ON "{{ wp_dbname }}".* TO '"{{ wp_dbuser }}"'@'%';"
  
