---
- name: update apt repo
  action: apt update-cache=yes
- name: install mysql-server
  action: apt pkg={{item}} state=installed
  with_items:
   - mysql-server
- name: restart mysql
  service:
   name: mysqld
   state: restarted
