---
- name: create security group
  ec2_group:
     name: eldar-sg
     description: Eldar Security group
     vpc_id: "{{ vpc.vpc_id }}"
     region: "{{ region }}"
     aws_secret_key: "{{ aws_secret_key }}"
     aws_access_key: "{{ aws_access_key }}"
     rules:
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 443
         to_port: 443
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 3306
         to_port: 3306
         cidr_ip: 172.22.2.0/24         
- name: Gather subnet facts and register them
  ec2_vpc_subnet_facts:
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    region: "{{ region }}"
    filters:
     vpc-id: "{{ vpc.vpc.id }}"
  register: vpc_subnet_facts
